CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

DELETE FROM todos;

ALTER TABLE todos ADD COLUMN user_id BIGINT NOT NULL REFERENCES users(id);
